### ISSUE TITLE
smtp.existingSecret mentioned in docs but not used

### ISSUE THREAD

**Issue by josefkorbel** [grafana/helm-charts#72]
According to the documentation, there is an option to specify smtp credentials with secret, however it is not used anywhere in the templates.

You can verify this on this search query https://github.com/grafana/helm-charts/search?q=existingSecret&type=code

**Comment by kivi** [comment]
I have a similar issue with Loki Stack
/charts/loki-stack

Could you please also add how you would create a secret? 
How to set the hostname?

**Comment by mindthevirt** [comment]
This is still an issue, even in the latest release.

**Comment by greg-mcnamara** [comment]
I can confirm that smtp.existingSecret does not work. Credentials are not extracted from the secret.

**Comment by druskus20** [comment]
I believe this is still the case, I am using kube-prometheus-stack

**Comment by XDavidT** [comment]
Workaround:
You can fill the SMTP on grafana.ini, for example:

```
  grafana:
    grafana.ini:
      smtp:
        enabled: true
        host: <host>:<port>
        skip_verify: true
        from_address: Sender@Email.com
        password:
        user:
```
full config doc here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#smtp

**Comment by druskus20** [comment]
> Workaround: You can fill the SMTP on grafana.ini, for example:
> 
> ```
>   grafana:
>     grafana.ini:
>       smtp:
>         enabled: true
>         host: <host>:<port>
>         skip_verify: true
>         from_address: Sender@Email.com
>         password:
>         user:
> ```
> 
> full config doc here: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#smtp

Yes, but this is still not a good enough solution. It means that you'd be hardcoding your SMTP credentials into the chart, and thus, into your version control system.

**Comment by mscdit** [comment]
Hi @druskus20 ... I also have trouble with this ... but I even can't get it working with the hardcoded solution.
I am using Grafana as sub chart in kube-prometheus-stack. If I specify password and user hardcoded I get the following error by deploying this with argoCD:

` Error: execution error at (kube-prometheus-stack/charts/grafana/templates/deployment.yaml:36:28): Sensitive key 'smtp.password' should not be defined explicitly in values. Use variable expansion instead`

So I think I am currently also stuck with the hardcoded solution as using existingSecret is not working neither the hardcoded version. Any hints to that?

THX, mscdit

**Comment by druskus20** [comment]
I went back to this recently.

```yaml
grafana:
  smtp:
    # `existingSecret` is a reference to an ALREADY EXISTING secret containing the smtp configuration
    # for Grafana.
    existingSecret: "grafana-smtp-auth"
    userKey: "user"
    passwordKey: "password"

  grafana.ini:
    log:
      level: debug
      mode: "file console"
    server:
      root_url: https://myurl.com
    smtp:
      enabled: true
      skip_verify: true # both true and false tried
      from_address: myaddr
      host: myhost
      # instead of putting it here, we can feed it a secret (above)
      #user: REDACTED
      #password: REDACTED
```
Do not mistake `grafana.smtp` with `grafana.grafana.ini.smtp`

We can then create this secret manually, or use something like SealedSecrets to encrypt it and store it safely in our version control system
```yaml
extraManifests: 
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: grafana-smtp-auth
      namespace: monitoring
    spec:
      encryptedData:
        password: REDACTED
        user: REDACTED 
      template:
          name: grafana-smtp-auth
          namespace: monitoring
        type: Opaque
```

This should result in:

```ini
# /etc/grafana/grafana.ini
# ...
[smtp]
enabled = true
from_address = REDACTED
host = REDACTED
skip_verify = true
```

And the environment variables `GF_SMTP_USER` and `GF_SMTP_PASSWORD` populated from our secret.
```bash
# env | grep GF
...
GF_SMTP_PASSWORD=REDACTED
GF_SMTP_USER=REDACTED
```

**However**

Grafana still fails to send the message:

![image](https://github.com/grafana/helm-charts/assets/43417195/17d6a06f-41f5-4e2f-9f11-adc60e86aac9)

**However, hardcoding `password` and `user` in grafana.ini, works. Looks to me like mixing both environment variables and grafana.ini (for smtp) is incompatible (though it should not be).** This is not a good workaround.

**Comment by druskus20** [comment]
Seems to me like this issue should be replaced by `SMTP Authentication: mixing both environment variables and grafana.ini is incompatible`. ? 

The title of the issue is misleading, as `existingSecret` is in fact working as intended, although maybe it is a bit misleading and should be specified that the secret **must** be created manually, outside of the grafana chart

**Comment by giovannicandido** [comment]
Is working but you have to config like that:

```yaml
grafana:
  smtp:
    existingSecret: "grafana-smtp-secret"
    passwordKey: "password"
    userKey: "user"
  grafana.ini:
    smtp:
      enabled: true
      host: host.com:587
      from_address: alerts@example.com
```

By the way, there is a orientation to put tripple quotes if you password has special characters, that is not necessary here.

**Comment by druskus20** [comment]
```yaml
grafana:
  smtp:
    existingSecret: "grafana-smtp-auth"
    userKey: "user"
    passwordKey: "password"
  grafana.ini:
    smtp:
      enabled: true
      skip_verify: true
      from_address: example@example
      host: host:587
```

This is not working for me. As I said, the values get populated as config files / env variables inside the container but the message sending still fails.

**Comment by avramenkovladyslav** [comment]
@druskus20, @giovannicandido 

I'm trying to configure SMTP at least with any configuration, but looks Grafana don't provision smtp configuration at all.
[Using this helm chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml) and this configuration for SMTP:

```
grafana.ini:
  smtp:
    enabled: true
    skip_verify: true
    from_address: grafana@domain.com
    host: email-smtp.eu-central-1.amazonaws.com:587
    user: "USERNAME"
    password: "PASSWORD"
```

Looks like that helm values for grafana.ini smtp exactly not existing but it should be like this, right?
I deployed this, checked the /etc/grafana/grafana.ini file, but there is not smtp field at all

**Comment by joelfernandes23** [comment]
This worked for me
`
grafana:
  grafana.ini:
    server:
      root_url: https://grafana.company.com    smtp:
      host: email-smtp.aws_region.amazonaws.com:587
      from_address: grafana@company.com
      enabled: "true"

  smtp:
    # `existingSecret` is a reference to an ALREADY EXISTING secret containing the smtp configuration
    # for Grafana.
    existingSecret: "grafana-smtp-secret"
    userKey: "user"
    passwordKey: "password"

  assertNoLeakedSecrets: true
`

**Comment by revoltez** [comment]
@druskus20 Have you found a solution? issue still happening with kube-prometheus-stack

**Comment by revoltez** [comment]
For anyone that came here from kube prometheus stack, this is grafana's alert manager not prometheus alert manager, if you don't configure your own prometheus AlertManager the alertmanager instance wouldn't even run.
